### ISSUE TITLE
List containing a single object not marshaled as an array

### ISSUE THREAD

**Issue by petercgrant** [derekdowling/go-json-spec-handler#20]
According to the jsonapi spec:

> A server MUST respond to a successful request to fetch a resource collection with an array of resource objects or an empty array (`[]`) as the response document's primary data.

The same type, `List`, is used to represent the `data` in  response to a request to fetch both a single resource and a collection of resources. This overloading causes a resource collection of length 1 to be marshaled as an object instead of as an array.

Source: https://github.com/derekdowling/go-json-spec-handler/blob/master/list.go#L73

**Comment by derekdowling** [comment]
Due to how this works, this is going to complicate things a bit more since as you mentioned you can't simply remove the case since the "List" type is dually coupled to two specification cases. This is probably going to require having two separate marshal types, "List" and "Object", in order to solve this problem. @petercgrant I've outlined a potential remediation in #21.

**Comment by petercgrant** [comment]
The cleanest way I can think of is making the current `Document` type always marshal to an array and add a new `Object` field that overrides that behavior. It requires some custom serialization. I'll send a PR shortly so we can evaluate the approach.

It looks like `ResourceLinkage` suffers from the same problem. To further complicate matters there, though, the jsonapi spec includes a case (empty to-one relationships) where `data` should be serialized as `null`:

> `null` is only an appropriate response when the requested URL is one that might correspond to a single resource, but doesn't currently.

We can solve that in a similar way but maybe leave out an `omitempty`. This comment will make more sense when you see the PR.

**Comment by derekdowling** [comment]
I believe both of these cases (Document and ResourceLinkage) are handled now. If not we will open a new one to track the latter.
