### ISSUE TITLE
Godep save fails

### ISSUE THREAD

**Issue by nscarlson** [derekdowling/go-json-spec-handler#24]
`godep save` fails on my project importing go-json-spec-handler:

```
godep: dirty working tree (please commit changes): /go/src/github.com/derekdowling/go-json-spec-handler
godep: error loading dependencies
```

**Comment by derekdowling** [comment]
It looks like you have uncommitted code and are attempting to save, which godep doesn't like. Have you already done `godep get github.com/derekdowling/go-json-spec-handler`? I can try to help you here, but it's going to be tough to reproduce. CI is passing, so I don't know that it is something with the project itself.

**Comment by nscarlson** [comment]
I'm running Go 1.6 and godep v41.  I'm at a clean state, tried completely clearing the `$GOPATH` directory, tried running `godep get github.com/derekdowling/go-json-spec-handler`

This _seems_ to be a related issue with godep: tools/godep#327

That would make sense, as this a bug with godep itself causing the vcs to enter a dirty state before completing.

**Comment by nscarlson** [comment]
I've confirmed this is an issue with go1.6.  Go1.5 works perfectly.  I'll close it now until you want to re-open this issue.

**Comment by nscarlson** [comment]
Running godep save ./... on my project causes go-json-spec-handler to enter the dirty state:

`modified: Godeps/_workspace/src/github.com/smartystreets/goconvey/web/client/resources/fonts/Open_Sans/LICENSE.txt`

To fix locally:

``` bash
cd $GOPATH/src/github.com/derekdowling/go-json-spec-handler
git add Godeps/_workspace/src/github.com/smartystreets/goconvey/web/client/resources/fonts/Open_Sans/LICENSE.txt
git commit -m "quick fix"
```

Now godep save works perfectly, and the godeps directoryin my project is generated as expected.

**Comment by derekdowling** [comment]
Okay, glad you got things working! Just to follow up, anything else I need to investigate on my end or is this resolved?

**Comment by nscarlson** [comment]
I'm referencing #25 because the aforementioned process shouldn't have to be performed every build to prevent CI from failing.  Best practice to keep all files using LF line endings, aye?
